---
- name: check prometheus postgres exporter installed
  stat: path="{{ prometheus_root_dir }}/{{ prometheus_postgres_exporter_release_name }}/postgres_exporter"
  register: installed_path

- name: download prometheus postgres exporter binary
  get_url:
    url: "{{ prometheus_postgres_exporter_download_url }}"
    dest: "{{ prometheus_root_dir }}/{{ prometheus_postgres_exporter_release_name }}.tar.gz"
  when: installed_path.stat.exists == false

- name: unarchive binary tarball
  unarchive:
    copy: no
    src: "{{ prometheus_root_dir }}/{{ prometheus_postgres_exporter_release_name }}.tar.gz"
    dest: "{{ prometheus_root_dir }}"
    creates: "{{ prometheus_root_dir }}/{{ prometheus_postgres_exporter_release_name }}/postgres_exporter"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  when: installed_path.stat.exists == false

- name: create symlink to the current release
  file:
    src: "{{ prometheus_root_dir }}/{{ prometheus_postgres_exporter_release_name }}/postgres_exporter"
    path: "/usr/local/bin/postgres_exporter"
    state: link
  notify:
    - restart postgres exporter

- name: create systemd service unit
  template:
    src: prometheus-postgres-exporter.service.j2
    dest: /etc/systemd/system/prometheus-postgres-exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postgres exporter

- meta: flush_handlers

- name: ensure prometheus postgres exporter service is enabled and started
  service:
    name: prometheus-postgres-exporter
    state: started
    enabled: yes
