---
prometheus_blackbox_exporter_version: 0.17.0
prometheus_blackbox_exporter_release_name: "blackbox_exporter-{{ prometheus_blackbox_exporter_version }}.linux-amd64"
prometheus_blackbox_exporter_download_url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ prometheus_blackbox_exporter_version }}/{{ prometheus_blackbox_exporter_release_name }}.tar.gz"
prometheus_blackbox_exporter_config_flags: {}
prometheus_blackbox_exporter_modules: {}
